import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>yungrari for Prawda bar</title>
        <meta name="description" content="Generated by yungrari ©" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{ marginBottom: 48 }}>
          <Image src="/tryzub.webp" alt="tryzub" width={200} height={200} />
        </div>

        <div style={{ alignSelf: 'stretch', marginBottom: 48 }}>
          <iframe
            width="100%"
            height="300"
            allow="autoplay"
            src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1408390762&color=%23ff5500&auto_play=true&hide_related=true&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"
            style={{ marginBottom: 8 }}
          />

          <div className={inter.className}>
            <a
              href="https://soundcloud.com/yungr4r1"
              title="yungrari"
              target="_blank"
              rel="noreferrer"
            >
              yungrari
            </a>{' '}
            ·{' '}
            <a
              href="https://soundcloud.com/yungr4r1/supportukraine"
              title="Freedom mix"
              target="_blank"
              rel="noreferrer"
            >
              Freedom mix for Krakow&apos;s &quot;Prawda bar&quot;
            </a>
          </div>
        </div>

        <div className={styles.code}>
          <p>
            <code>#WeAreUkraine</code>
          </p>

          <p>
            <code>#StandWithUkraine</code>
          </p>

          <div>
            <Image
              src="/savelife_qr_code.png"
              alt="savelife.in.ua"
              width={100}
              height={100}
            />
          </div>
        </div>
      </main>
    </>
  )
}
